apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/component: app
  app.kubernetes.io/managed-by: ArgoCD
  app.kubernetes.io/created-by: ArgoCD
