apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - daemonSet.yaml

configMapGenerator:
  - name: filebeat-config
    files:
      - filebeat.yml

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app.kubernetes.io/name: filebeat