apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: main
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-upload-configuration
                  key: POSTGRES_HOST
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-upload-configuration
                  key: POSTGRES_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-upload-credentials
                  key: POSTGRES_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-upload-credentials
                  key: POSTGRES_PASSWORD