# Manual a-priori configuration. Configuration will be only used when the sensor
# is actually installed by the agent.
# The commented out example values represent example configuration and are not
# necessarily defaults. Defaults are usually 'absent' or mentioned separately.
# Changes are hot reloaded unless otherwise mentioned.

# It is possible to create files called 'configuration-abc.yaml' which are
# merged with this file in file system order. So 'configuration-cde.yaml' comes
# after 'configuration-abc.yaml'. Only nested structures are merged, values are
# overwritten by subsequent configurations.

# Secrets
# To filter sensitive data from collection by the agent, all sensors respect
# the following secrets configuration. If a key collected by a sensor matches
# an entry from the list, the value is redacted.
#com.instana.secrets:
#  matcher: 'contains-ignore-case' # 'contains-ignore-case', 'contains', 'regex'
#  list:
#    - 'key'
#    - 'password'
#    - 'secret'

# Host
#com.instana.plugin.host:
#  tags:
#    - 'dev'
#    - 'app1'

# Hardware & Zone
#com.instana.plugin.generic.hardware:
#  enabled: true # disabled by default
#  availability-zone: 'zone'
com.instana.plugin.activemqartemis:
  monitorQueues:
    - 'upload-ready-for-processing::aggregator'
    - 'aggregator'
    - 'upload-ready-for-processing'
com.instana.plugin.prometheus:
  # Global (all) endpoints username/password configuration (optional)
  username: ''
  password: ''
  customMetricSources:
    - url: '/q/metrics'
      metricNameIncludeRegex: '.*'
com.instana.plugin.postgresql:
  user: 'postgres'
  password: 'postgres'
  database: ''
com.instana.plugin.opentelemetry:
  enabled: true
com.instana.tracing:
  extra-http-headers:
    - 'X-Correlation-ID'