apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: main
          image: docker.elastic.co/kibana/kibana-oss:7.10.2
          ports:
            - containerPort: 5601