apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app.kubernetes.io/name: prometheus
  app.kubernetes.io/version: '2.36.0'