apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash-oss:7.10.2
          ports:
            - containerPort: 5044
              name: logstash
            - containerPort: 9600
              name: http
          command:
            - logstash
          volumeMounts:
            - mountPath: /usr/share/logstash/pipeline
              name: logstash-config
      volumes:
        - name: logstash-config
          configMap:
            name: logstash-config