apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: main
          image: docker.elastic.co/logstash/logstash-oss:7.10.2
          ports:
            - containerPort: 12201
              protocol: UDP
            - containerPort: 5000
            - containerPort: 9600
          volumeMounts:
            - mountPath: /usr/share/logstash/pipeline
              name: logstash-config
      volumes:
        - name: logstash-config
          configMap:
            name: logstash-gelf-config