apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  ports:
    - name: gelf
      protocol: UDP
      port: 12201
    - name: logstash
      protocol: TCP
      port: 5000
    - name: api
      protocol: TCP
      port: 9600