apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: jaeger
  app.kubernetes.io/version: '1.35.1'
  app.kubernetes.io/component: tracing
  app.kubernetes.io/managed-by: ArgoCD
  app.kubernetes.io/created-by: ArgoCD
