apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 16686
    - name: jaeger
      protocol: TCP
      port: 14268