apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: s4-triggertemplate
spec:
  params:
    - name: git-repository-revision
      description: The git revision
      default: master
    - name: git-repository-url
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: github-
      spec:
        serviceAccountName: tekton-triggers-sa
        pipelineRef:
          name: java-build-push-commit
        params:
          - name: code-repo-url
            value: $(tt.params.git-repository-url)
          - name: code-repo-revision
            value: $(tt.params.git-repository-revision)
          - name: infra-repo-url
            value: 'https://github.com/ConSol/s4-infra'
          - name: infra-repo-revision
            value: main
        workspaces:
          - name: code
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: infra
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: git-credentials
            secret:
              secretName: github-credentials
          - name: maven-settings-and-cache
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: s4-pipelinebinding
spec:
  params:
    - name: git-repository-url
      value: $(body.repository.clone_url)
    - name: git-repository-revision
      value: $(body.head_commit.id)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: s4-listener
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - bindings:
        - ref: s4-pipelinebinding
      template:
        ref: s4-triggertemplate