apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: s4-triggertemplate
  namespace: s4-pipelines
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: namespace
      description: The namespace to create the resources
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: github-
        namespace: $(tt.params.namespace)
      spec:
        serviceAccountName: tekton-triggers-sa
        pipelineRef:
          name: java-build-push-commit
        resources:
          - name: code-repo-
            resourceSpec:
              type: git
              params:
                - name: revision
                  value: $(tt.params.gitrevision)
                - name: url
                  value: $(tt.params.gitrepositoryurl)
          - name: infra-repo
            resourceSpec:
              type: git
              params:
                - name: revision
                  value: main
                - name: url
                  value: https://github.com/ConSol/s4-infra
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: s4-pipelinebinding
  namespace: s4-pipelines
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: namespace
      value: s4-pipelines
    - name: gitrepositoryurl
      value: "https://github.com/$(body.repository.full_name)"
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: s4-listener
  namespace: s4-pipelines
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - bindings:
        - ref: s4-pipelinebinding
      template:
        ref: s4-triggertemplate