apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: java-build-push-commit
spec:
  params:
    - name: code-repo-url
      type: string
    - name: code-repo-revision
      type: string
    - name: infra-repo-url
      type: string
    - name: infra-repo-revision
      type: string
  workspaces:
    - name: code
    - name: infra
    - name: maven-settings-and-cache
    - name: git-credentials
  tasks:
    - name: clone-code
      taskRef:
        kind: Task
        name: git-clone
      params:
        - name: url
          value: $(params.code-repo-url)
        - name: revision
          value: $(params.code-repo-revision)
      workspaces:
        - name: output
          workspace: code
    - name: clone-infra
      taskRef:
        kind: Task
        name: git-clone
      params:
        - name: url
          value: $(params.infra-repo-url)
        - name: revision
          value: $(params.infra-repo-revision)
      workspaces:
        - name: output
          workspace: infra
    - name: build
      taskRef:
        kind: Task
        name: maven
      runAfter:
        - clone-code
      params:
        - name: MAVEN_IMAGE
          # 3-eclipse-temurin-17
          value: maven@sha256:7e8eb04644e82fafbf46b10fed81e3c46b067ea7bd27af4260fae9b4e98256fd
        - name: GOALS
          value:
            - clean
            - install
            - -Dmaven.repo.local=$(workspaces.maven-settings-and-cache.path)
            - -DskipTests
      workspaces:
        - name: source
          workspace: code
        - name: maven-settings
          workspace: maven-settings-and-cache
    - name: build-and-push-aggregator-image
      taskRef:
        kind: Task
        name: kaniko
      runAfter:
        - build
      params:
        - name: IMAGE
          value: '935491670310.dkr.ecr.eu-central-1.amazonaws.com/s4/aggregator:$(tasks.clone-code.results.commit-short)'
        - name: DOCKERFILE
          value: './dockerfiles/Dockerfile.quarkus-ubi'
        - name: CONTEXT
          value: './services/aggregator'
      workspaces:
        - name: source
          workspace: code
    - name: build-and-push-continuous-test-image
      taskRef:
        kind: Task
        name: kaniko
      runAfter:
        - build
      params:
        - name: IMAGE
          value: '935491670310.dkr.ecr.eu-central-1.amazonaws.com/s4/continuous-test:$(tasks.clone-code.results.commit-short)'
        - name: DOCKERFILE
          value: './dockerfiles/Dockerfile.ubi'
        - name: CONTEXT
          value: './citrus-tests/continuous'
        - name: AWS_SDK_LOAD_CONFIG
          value: true
        - name: AWS_EC2_METADATA_DISABLED
          value: false
      workspaces:
        - name: source
          workspace: code
    - name: build-and-push-rest-api-image
      taskRef:
        kind: Task
        name: kaniko
      runAfter:
        - build
      params:
        - name: IMAGE
          value: '935491670310.dkr.ecr.eu-central-1.amazonaws.com/s4/rest-api:$(tasks.clone-code.results.commit-short)'
        - name: DOCKERFILE
          value: './dockerfiles/Dockerfile.quarkus-ubi'
        - name: CONTEXT
          value: './services/rest-api'
        - name: AWS_SDK_LOAD_CONFIG
          value: true
        - name: AWS_EC2_METADATA_DISABLED
          value: false
      workspaces:
        - name: source
          workspace: code
    - name: patch-deployment-images
      taskRef:
        kind: Task
        name: bash
      runAfter:
        - build-and-push-aggregator-image
        - build-and-push-rest-api-image
        - build-and-push-continuous-test-image
      params:
        - name: command
          value: |
            commit_short=$(tasks.clone-code.results.commit-short);
            sed -i "s@\(image:\s\+\)[a-zA-Z0-9_/.:-]*@\1935491670310.dkr.ecr.eu-central-1.amazonaws.com/s4/aggregator:${commit_short}@g" \
              deployments/overlays/aggregator/generated-image-patch.yaml;
            sed -i "s@\(image:\s\+\)[a-zA-Z0-9_/.:-]*@\1935491670310.dkr.ecr.eu-central-1.amazonaws.com/s4/continuous-test:${commit_short}@g" \
              deployments/overlays/continuous-test/generated-image-patch.yaml;
            sed -i "s@\(image:\s\+\)[a-zA-Z0-9_/.:-]*@\1935491670310.dkr.ecr.eu-central-1.amazonaws.com/s4/rest-api:${commit_short}@g" \
              deployments/overlays/rest-api/generated-image-patch.yaml;
      workspaces:
        - name: source
          workspace: infra
    - name: commit-and-push-to-infra
      taskRef:
        kind: Task
        name: git-cli
      runAfter:
        - patch-deployment-images
      params:
        - name: GIT_USER_NAME
          value: tekton-pusher
        - name: GIT_USER_EMAIL
          value: tekton@pipe.line
        - name: GIT_SCRIPT
          value: |
            git checkout main
            git pull
            git add deployments/overlays/aggregator/generated-image-patch.yaml
            git add deployments/overlays/continuous-test/generated-image-patch.yaml
            git add deployments/overlays/rest-api/generated-image-patch.yaml
            git commit -m "commit $(tasks.clone-code.results.commit-short): updating images"
            git push -u origin
      workspaces:
        - name: source
          workspace: infra
        - name: basic-auth
          workspace: git-credentials