apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: java-build-push-commit
spec:
  params:
    - name: code-repo
      type: git
    - name: infra-repo
      type: git
  workspaces:
    - code
    - infra
  tasks:
    - name: clone-code
      taskRef:
        name: git-clone
      params:
        - name: url
          value: ${params.code-repo.url}
        - name: revision
          value: ${params.code-repo.revision}
      workspaces:
        - name: output
          workspace: code
    - name: clone-infra
      taskRef:
        name: git-clone
      params:
        - name: url
          value: ${params.infra-repo.url}
        - name: revision
          value: ${params.infra-repo.revision}
      workspaces:
        - name: output
          workspace: infra
