apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases/quarkus-app

components:
  - ../../components/patches/configs/artemis
  - ../../components/patches/configs/postgres

patchesStrategicMerge:
  - generated-image-patch.yaml

namePrefix: aggregator-

commonLabels:
  app.kubernetes.io/name: aggregator
  app.kubernetes.io/version: '1.0'
