apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases/app

components:
  - ../../components/patches/configs/artemis
  - ../../components/patches/configs/postgres
  - ../../components/patches/configs/tracing
  - ../../components/patches/configs/logging

patchesStrategicMerge:
  - generated-image-patch.yaml
  - environment-patch.yaml

namePrefix: aggregator-

commonLabels:
  app.kubernetes.io/name: aggregator-app
  app.kubernetes.io/version: '1.0'
  app.kubernetes.io/component: s4
  app.kubernetes.io/managed-by: ArgoCD
  app.kubernetes.io/created-by: ArgoCD
