- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: GELF_ENABLED
    value: 'false'
- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: CONSOLE_LOG_JSON
    value: 'true'