apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: main
          ports:
            - containerPort: 8080
          env:
            - name: GELF_HOST
              value: logstash
            - name: GELF_PORT
              value: 12201