piVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: artemis
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: a80251b4396b9428d8898f2e34e92313-1929712141.eu-central-1.elb.amazonaws.com
      http:
        paths:
          - path: /artemis(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: artemis
                port:
                  name: http