apiVersion: v1
kind: Service
metadata:
  name: artemis
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8161
    - protocol: TCP
      port: 61616
    - protocol: TCP
      port: 5672