apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: main
          image: 935491670310.dkr.ecr.eu-central-1.amazonaws.com/s4/rest-api:4ba24fa