apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - elastic
  - filebeat
  - kibana
  - logstash

commonLabels:
  app.kubernetes.io/version: 7.10.2
  app.kubernetes.io/component: system-logging
  app.kubernetes.io/managed-by: ArgoCD
  app.kubernetes.io/created-by: ArgoCD
