apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: main
          env:
            - name: TRACING_ENDPOINT
              value: http://instana-agent:42699/com.instana.plugin.jaeger.trace