apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: main
          ports:
            - containerPort: 8080
          env:
            - name: AMQP_HOST
              valueFrom:
                configMapKeyRef:
                  name: artemis-configuration
                  key: ARTEMIS_HOST
            - name: AMQP_PORT
              valueFrom:
                configMapKeyRef:
                  name: artemis-configuration
                  key: ARTEMIS_PORT
            - name: AMQP_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: artemis-credentials
                  key: ARTEMIS_USERNAME
            - name: AMQP_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: artemis-credentials
                  key: ARTEMIS_PASSWORD