apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: main
          ports:
            - containerPort: 8080
          env:
            - name: SUT_URL
              value: http://rest-api
          command:
            - "--engine"
            - "testng"
            - "--test"
            - "de.consol.dus.s4.citrus.tests.continuous.UploadIT"
            - "--duration"
            - "2147483647"