apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: main
          image: public.ecr.aws/j6e0o7d4/s4/continuous-test:fa9dd54