apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

configMapGenerator:
  - name: citrus-config
    envs:
      - citrus-config.env

generatorOptions:
  disableNameSuffixHash: true

patchesStrategicMerge:
  - generated-image-patch.yaml

namePrefix: continuous-test-app

commonLabels:
  app.kubernetes.io/name: continuous-test-app
  app.kubernetes.io/version: '1.0'
  app.kubernetes.io/component: tests
  app.kubernetes.io/managed-by: ArgoCD
  app.kubernetes.io/created-by: ArgoCD
