apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

components:
  - ../../components/pod/health/citrus

configMapGenerator:
  - name: citrus-config
    envs:
      - citrus-config.env

generatorOptions:
  disableNameSuffixHash: true

patchesStrategicMerge:
  - generated-image-patch.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: app
    path: patch-container-name.yaml

namePrefix: continuous-test-

commonLabels:
  app.kubernetes.io/name: continuous-test-app
  app.kubernetes.io/version: '1.0'
  app.kubernetes.io/component: tests
  app.kubernetes.io/managed-by: ArgoCD
  app.kubernetes.io/created-by: ArgoCD
