{
 "title": "CPU and Memory",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "deployment", "query": "rest-api, aggregator" }
  ]
 },
 "panels": [
  { "title": "${deployment}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "deployment" },
  {
   "title": "RSS Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_memory_rss_bytes{instance=\"${deployment}\"}",
     "legendFormat": "RSS Memory"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"${deployment}\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"${deployment}\"}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{instance=\"${deployment}\"}",
     "legendFormat": "live threads"
    },
    {
     "expr": "jvm_threads_daemon_threads{instance=\"${deployment}\"}",
     "legendFormat": "daemon threads"
    }
   ]
  }
 ]
}