apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: application-dashboards
    files:
      - cpu-and-memory-dashboard.json
  - name: grafana-dashboards
    files:
      - dashboards.yml
  - name: grafana-datasources
    files:
      - prometheus.yml

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app.kubernetes.io/name: grafana